Update to jupyter collaboration 3
jupyterlab/jupyter-chat pull request #94
Opened 2024-10-29 17:18 UTC by brichet

2024-12-04 18:09 UTC, dlqqq commented
Motivation for this change (authored by @brichet in a private conversation):

It is related to https://github.com/jupyterlab/jupyter-collaboration/pull/379, that should be in soon, and adds a widget to display the current users of a collaborative document.
IIRC this PR can't be backported to jupyter-collaboration 2 because of its dependencies to jupyter/ydoc .

2024-12-17 21:50 UTC, dlqqq requested changes
@brichet Thank you for working on this while I was away! Left a few points of feedback below.

2024-12-18 00:14 UTC, dlqqq commented
BTW you may have to close & re-open this PR to re-run the workflows. I noticed the readthedocs workflows stalled for PRs opened last week, but the issue should be fixed now.

2024-12-18 15:37 UTC, brichet commented on packages/jupyterlab-chat/package.json
> +    "@jupyter/ydoc": "^2.0.0 || ^3.0.0",
It is just to get aligned with `@jupyter/collaborative-drive` dependencies, which support both.
We can probably drop support for version 2.

2024-12-18 15:44 UTC, brichet commented on packages/jupyterlab-chat/src/ychat.ts
> +  setSource(value: JSONObject): void {
It is required in `@jupyter/ydoc` >= 3
https://github.com/jupyter-server/jupyter_ydoc/blob/43532219006844c16dcccb4f9831daf7ef11995e/javascript/src/ydocument.ts#L171

2024-12-18 15:45 UTC, brichet commented on packages/jupyterlab-chat/src/ychat.ts
> +  getSource(): JSONObject {
I don't think, it must be `JSONValue | string`, as described in the `YDocument` https://github.com/jupyter-server/jupyter_ydoc/blob/43532219006844c16dcccb4f9831daf7ef11995e/javascript/src/ydocument.ts#L171

2024-12-18 15:45 UTC, brichet commented
Bump CI

2024-12-18 16:35 UTC, dlqqq approved these changes
Awesome, TY for answering my feedback so thoughtfully!

2024-12-19 16:25 UTC, merged